[package]
name = "bumblebee"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.6.1"
aws-sdk-s3 = "1.82.0"
aws-sdk-sqs = "1.64.0"
duckdb = { version = "1.2.1", features = ["bundled"] }
tokio = { version = "1.44.2", features = ["full"] }
